# This is a basic workflow to help you get started with Actions

name: Data

on:
  schedule: 
      - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.4.3"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install
      - name: Run script
        run: yarn sc get-pob-data
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: data/*.json
          commit_message: "chore: Update data files"
