name: Pull Requests

on:
  pull_request:
    paths:
      - 'app/**'

jobs:
  expo-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install packages
        run: yarn --cwd app install
      - run: cd app && expo publish --release-channel=pr-${{ github.event.number }}
      - uses: unsplash/comment-on-pr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: App is ready for review, you can [see it here](https://expo.io/@maaael/path-of-building-app?release-channel=pr-${{ github.event.number }}).
